# Generated by Django 5.2.8 on 2026-05-09 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='اسم المشروع')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف المشروع')),
                ('start_date', models.DateField(verbose_name='تاريخ البدء')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('ongoing', 'جاري العمل'), ('completed', 'مكتمل'), ('on_hold', 'متوقف مؤقتاً')], default='pending', max_length=20, verbose_name='حالة المشروع')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'مشروع',
                'verbose_name_plural': 'المشاريع',
            },
        ),
    ]
