# Generated by Django 5.2.8 on 2026-05-10 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_customer_digitalarchive_employee_finance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='created_at',
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='وصف المشروع'),
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='صورة المشروع'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(max_length=50, verbose_name='الحالة'),
        ),
    ]
