# Generated by Django 5.2.8 on 2026-05-10 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_project_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='service_type',
        ),
        migrations.AddField(
            model_name='finance',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.project', verbose_name='مشروع مرتبط'),
        ),
        migrations.AddField(
            model_name='order',
            name='item_name',
            field=models.CharField(default=0, max_length=100, verbose_name='اسم الصنف'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='السعر'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=200, verbose_name='اسم الزبون'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='digitalarchive',
            name='final_file',
            field=models.FileField(upload_to='archive/', verbose_name='الملف النهائي'),
        ),
        migrations.AlterField(
            model_name='digitalarchive',
            name='project_name',
            field=models.CharField(max_length=200, verbose_name='اسم المشروع المؤرشف'),
        ),
        migrations.AlterField(
            model_name='digitalarchive',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الأرشفة'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='joined_at',
            field=models.DateField(auto_now_add=True, verbose_name='تاريخ التعيين'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=200, verbose_name='اسم الموظف'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(max_length=100, verbose_name='المسمى الوظيفي'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المرتب'),
        ),
        migrations.AlterField(
            model_name='finance',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ'),
        ),
        migrations.AlterField(
            model_name='finance',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='finance',
            name='title',
            field=models.CharField(max_length=200, verbose_name='البيان'),
        ),
        migrations.AlterField(
            model_name='finance',
            name='type',
            field=models.CharField(choices=[('income', 'إيراد'), ('expense', 'مصروف')], max_length=10, verbose_name='نوع العملية'),
        ),
        migrations.AlterField(
            model_name='galleryproject',
            name='category',
            field=models.CharField(max_length=100, verbose_name='التصنيف'),
        ),
        migrations.AlterField(
            model_name='galleryproject',
            name='description',
            field=models.TextField(verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='galleryproject',
            name='image',
            field=models.ImageField(upload_to='gallery/', verbose_name='الصورة'),
        ),
        migrations.AlterField(
            model_name='galleryproject',
            name='title',
            field=models.CharField(max_length=200, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='management.customer', verbose_name='الزبون'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'جديد'), ('processing', 'قيد التنفيذ'), ('completed', 'مكتمل')], default='new', max_length=20, verbose_name='حالة الطلب'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('جاري العمل', 'جاري العمل'), ('مكتمل', 'مكتمل'), ('pending', 'قيد الانتظار')], default='pending', max_length=50, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='date',
            field=models.DateField(verbose_name='تاريخ الشراء'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='item_name',
            field=models.CharField(max_length=200, verbose_name='اسم المادة/الغرض'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='supplier',
            field=models.CharField(max_length=200, verbose_name='المورد'),
        ),
    ]
