# Generated by Django 5.2.8 on 2026-05-10 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_remove_order_service_type_finance_project_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='order_attachments/', verbose_name='المرفقات (مستندات/صور)'),
        ),
        migrations.AddField(
            model_name='order',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='الموعد النهائي المتوقع'),
        ),
        migrations.AddField(
            model_name='order',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='وصف تفصيلي للطلب'),
        ),
        migrations.AddField(
            model_name='order',
            name='recorded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='الموظف المسؤول عن الإدخال'),
        ),
        migrations.AddField(
            model_name='order',
            name='title',
            field=models.CharField(default=0, help_text='مثال: تصميم موقع لشركة X', max_length=200, verbose_name='عنوان الطلب/المشروع'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ ووقت الإدخال'),
        ),
        migrations.AlterField(
            model_name='order',
            name='item_name',
            field=models.CharField(max_length=100, verbose_name='نوع الخدمة/الصنف'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='الميزانية التقديرية'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'جديد - قيد المراجعة الإدارية'), ('accepted', 'مقبول - تم التحويل للتنفيذ'), ('processing', 'قيد التنفيذ الفعلي'), ('rejected', 'مرفوض'), ('completed', 'مكتمل - جاهز للتسليم')], default='new', max_length=20, verbose_name='حالة الطلب'),
        ),
    ]
