# Generated by Django 5.2.8 on 2026-05-10 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_order_attachments_order_deadline_order_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='manual_customer_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='اسم الزبون (إدخال يدوي)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='order_attachments/', verbose_name='المرفقات'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإدخال'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='management.customer', verbose_name='الزبون المسجل'),
        ),
        migrations.AlterField(
            model_name='order',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='الموعد النهائي'),
        ),
        migrations.AlterField(
            model_name='order',
            name='item_name',
            field=models.CharField(max_length=100, verbose_name='نوع الخدمة/الأصناف'),
        ),
        migrations.AlterField(
            model_name='order',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='الموظف المسؤول'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'جديد - قيد المراجعة'), ('accepted', 'مقبول - تم التحويل'), ('processing', 'قيد التنفيذ الفعلي'), ('rejected', 'مرفوض'), ('completed', 'مكتمل')], default='new', max_length=20, verbose_name='حالة الطلب'),
        ),
        migrations.AlterField(
            model_name='order',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان الطلب/المشروع'),
        ),
    ]
