# Generated by Django 5.2.8 on 2026-05-10 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_order_manual_customer_name_alter_order_attachments_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='GalleryProject',
        ),
        migrations.RemoveField(
            model_name='finance',
            name='project',
        ),
        migrations.RemoveField(
            model_name='order',
            name='attachments',
        ),
        migrations.AddField(
            model_name='digitalarchive',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.order', verbose_name='الطلب المرتبط'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchase',
            name='category',
            field=models.CharField(choices=[('أجهزة', 'أجهزة'), ('برمجيات', 'برمجيات'), ('خدمات خارجية', 'خدمات خارجية'), ('قرطاسية', 'قرطاسية')], default='أخرى', max_length=50, verbose_name='تصنيف المشتريات'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='اعتماد الإدارة'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='management.order', verbose_name='مرتبط بطلب زبون'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='purchased_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='الموظف المسؤول عن الشراء'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AlterField(
            model_name='digitalarchive',
            name='final_file',
            field=models.FileField(upload_to='archive/', verbose_name='الملف النهائي/العقد'),
        ),
        migrations.AlterField(
            model_name='finance',
            name='type',
            field=models.CharField(choices=[('income', 'إيراد (دخل)'), ('expense', 'مصروف (مشتريات/رواتب)')], max_length=10, verbose_name='نوع العملية'),
        ),
        migrations.AlterField(
            model_name='order',
            name='item_name',
            field=models.CharField(max_length=100, verbose_name='نوع الخدمة (أصناف)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='الميزانية المتفق عليها'),
        ),
        migrations.AlterField(
            model_name='order',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='الموظف الذي استلم الطلب'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='item_name',
            field=models.CharField(max_length=200, verbose_name='الغرض المطلوب شراؤه'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='تكلفة الشراء'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='supplier',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='المورد/المحل'),
        ),
    ]
