# Generated by Django 5.2.8 on 2026-05-10 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_delete_galleryproject_remove_finance_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='order_attachments/', verbose_name='المرفقات'),
        ),
    ]
