# Generated by Django 5.2.8 on 2026-05-11 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_order_attachments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='digitalarchive',
            name='final_file',
        ),
        migrations.RemoveField(
            model_name='digitalarchive',
            name='project_name',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='digitalarchive',
            name='file',
            field=models.FileField(default=0, upload_to='archive/', verbose_name='الملف المؤرشف'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='digitalarchive',
            name='file_type',
            field=models.CharField(choices=[('عقد', 'عقد'), ('تصميم', 'تصميم'), ('كود', 'برمجيات'), ('أخرى', 'أخرى')], default='أخرى', max_length=50),
        ),
        migrations.AddField(
            model_name='digitalarchive',
            name='title',
            field=models.CharField(default=0, max_length=200, verbose_name='عنوان الملف'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='على رأس العمل'),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='رقم التواصل'),
        ),
        migrations.AddField(
            model_name='finance',
            name='category',
            field=models.CharField(default='عام', max_length=100, verbose_name='التصنيف المالي'),
        ),
        migrations.AddField(
            model_name='finance',
            name='related_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.order'),
        ),
        migrations.AddField(
            model_name='finance',
            name='related_purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.purchase'),
        ),
        migrations.AlterField(
            model_name='digitalarchive',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.order', verbose_name='الطلب المرتبط'),
        ),
        migrations.AlterField(
            model_name='digitalarchive',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='joined_at',
            field=models.DateField(verbose_name='تاريخ التعيين'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(max_length=100, verbose_name='المسمى الوظيفي/التخصص'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المرتب الأساسي'),
        ),
        migrations.AlterField(
            model_name='finance',
            name='type',
            field=models.CharField(choices=[('income', 'إيراد (داخل)'), ('expense', 'مصروف (خارج)')], max_length=10, verbose_name='نوع العملية'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='موعد التسليم'),
        ),
        migrations.AlterField(
            model_name='order',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='وصف الطلب'),
        ),
        migrations.AlterField(
            model_name='order',
            name='item_name',
            field=models.CharField(max_length=100, verbose_name='الصنف/الخدمة'),
        ),
        migrations.AlterField(
            model_name='order',
            name='manual_customer_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='اسم الزبون (يدوي)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='الميزانية (د.ل)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='الموظف المستلم'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'جديد'), ('processing', 'قيد التنفيذ'), ('completed', 'مكتمل'), ('archived', 'مؤرشف')], default='new', max_length=20, verbose_name='حالة الطلب'),
        ),
        migrations.AlterField(
            model_name='order',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان الطلب'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='category',
            field=models.CharField(choices=[('أجهزة', 'أجهزة'), ('برمجيات', 'برمجيات'), ('خدمات خارجية', 'خدمات خارجية'), ('أخرى', 'أخرى')], default='أخرى', max_length=50),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='item_name',
            field=models.CharField(max_length=200, verbose_name='الغرض'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='management.order', verbose_name='مرتبط بطلب'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='التكلفة'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchased_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='supplier',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='المورد'),
        ),
    ]
