# Generated by Django 5.2.8 on 2026-05-13 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_remove_digitalarchive_final_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='national_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='الرقم الوطني'),
        ),
    ]
